### ISSUE TITLE
Coverage of all basic classes in `covid19_sir/model` in unit tests

### ISSUE THREAD

**Issue by andre-senna** [singnet/covid-simulation#89]

**Comment by deborahduong** [comment]
@andre-senna I have unit tests set up that are particular to analysis that I created for the reputation simulation that I can show you.  They allow a range of values, and dont crash but give a warning, so that all values may be checked.  The acceptable ranges are parameterized in a json file. I would be happy to show this to the group

**Comment by ramongduraes** [comment]
Solved by PRs #117 #118 and #120
